import os
Import('env lib')

# clone environment and add libraries for modules
menv = env.Clone()
menv.Append(CPPPATH=['#'],
            LIBS=['jack','samplerate','hdf5','hdf5_hl','sndfile',
                  # need to auto-detect this
                  'boost_system','boost_date_time','boost_program_options','boost_filesystem'])

out = [menv.Program(os.path.splitext(str(f))[0],[f,lib]) for f in env.Glob("*.cc")] + \
    [menv.Program(os.path.splitext(str(f))[0],[f]) for f in env.Glob("*.c")]

env.Alias('test',out)


