import os

# debug flags for compliation
debug = ARGUMENTS.get('debug',1)

if hasattr(os,'uname'):
    system = os.uname()[0]
else:
    system = 'Windows'
    
env = Environment(CPPPATH=['..'],
                  CCFLAGS=['-Wall'],
                  LIBPATH=['../jill'],
                  LIBS=['jack','jill','sndfile','samplerate','boost_date_time','boost_program_options'],
                  tools=['default'])

if system=='Darwin':
    env.Append(CPPPATH=['/opt/local/include'],
               LIBPATH=['/opt/local/lib'])
else:
    env.Append(LIBS=['boost_thread'])

if int(debug):
    env.Append(CCFLAGS=['-g2'])
else:
    env.Append(CCFLAGS=['-O2'])

#test = env.Program('capture_test',['capture_test.cc','trigger_writer.cc'])
prog = env.Program('capture', ['capture.cc', 'trigger_writer.cc'])
