import os

# debug flags for compliation
debug = ARGUMENTS.get('debug',1)

if hasattr(os,'uname'):
  system = os.uname()[0]
else:
  system = 'Windows'

vars = Variables()
vars.Add('dio_support', 'Set to 1 to include support for DIO switch triggered playback', 0)
    
env = Environment(variables = vars,
                  CPPPATH=['..'],
                  CCFLAGS=['-Wall'],
                  LIBPATH=['../jill'],
                  LIBS=['jack','jill','sndfile','samplerate','boost_date_time','boost_program_options'],
                  tools=['default'])

dio_support = ARGUMENTS.get('dio_support',0)
if dio_support:
  env.Append(CPPDEFINES={'DIO_SUPPORT' : '${dio_support}'})

if system=='Darwin':
  env.Append(CPPPATH=['/opt/local/include'],
             LIBPATH=['/opt/local/lib'],
             LIBS=['boost_thread-mt'])
else:
  env.Append(LIBS=['boost_thread'])

if int(debug):
  env.Append(CCFLAGS=['-g2'])
else:
  env.Append(CCFLAGS=['-O2'])

sapsucker_files = ['sapsucker.cc', 
                   'switch_tracker.cc', 
                   'trigger_writer.cc', 
                   'keypress_switch.cc', 
                   'sapsucker_multi_sndfile.cc', 
                   'quotas.cc']
if dio_support:
  env.Append(LIBS=['jack','jill','sndfile','samplerate','boost_date_time','boost_program_options','comedi'])
  sapsucker_files.append('nidaq_dio_switch.cc')

prog = env.Program('window_discriminator', ['window_discriminator.cc'])
prog = env.Program('capture', ['capture.cc', 'trigger_writer.cc'])
prog = env.Program('keypress_test', ['keypress_test.cc', 'keypress_switch.cc'])
prog = env.Program('quota_test', ['quota_test.cc','quotas.cc'])
if dio_support:
  prog = env.Program('dio_switch_test', ['dio_switch_test.cc', 'nidaq_dio_switch.cc'])
prog = env.Program('sapsucker', sapsucker_files)
#
