import os
Import('env lib')

if hasattr(os,'uname'):
    system = os.uname()[0]
else:
    system = 'Windows'

menv = env.Clone()
menv.Append(CPPPATH=['#'],
            LIBS=['jack','jill','sndfile','samplerate','boost_date_time','boost_program_options'])

if not system=='Darwin':
   env.Append(LIBS=['boost_thread'])

prog = menv.Program('capture', ['capture.cc', 'trigger_writer.cc'])

Return('prog')
