Import("env lib")

# jack, samplerate, sndfile and zmq come from pkg-config in the SConstruct;
# the Boost library names were resolved there as well.
menv = env.Clone()
menv.Append(
    CPPPATH=["#"],
    LIBS=["pthread"] + env["BOOST_LIBS"],
)

programs = {
    "jdelay": "jdelay.cc",
    "jamnoise": "jamnoise.cc",
    "jnoise": "jnoise.cc",
    "jdetect": "jdetect.cc",
    "jtime": "jtime.cc",
    "jstim": "jstim.cc",
    "jstimserver": "jstimserver.cc",
    "jclicker": "jclicker.cc",
    "jrelay": "jrelay.cc",
    "jmonitor": "monitor_client.c",
}

if GetOption("compile_arf"):
    menv.Append(LIBS=["hdf5", "hdf5_hl"])
    programs["jrecord"] = "jrecord.cc"


out = []

for progname, src in programs.items():
    prog = menv.Program(progname, [src, lib])
    menv.Alias(progname, prog)
    out.append(prog)
    env.Alias("install", env.Install(env["BINDIR"], prog))

env.Alias("modules", out)
