import os
Import('env lib')

menv = env.Clone()
menv.Append(CPPPATH=['#'],LIBS=['sndfile','boost_date_time',
	 			'boost_program_options'])

programs = {'mixer' : ['mixer.cc'],
            'delay' : ['delay.cc'],
            'writer' : ['writer.cc'],
            'twriter' : ['triggered_writer.cc', 'trigger_classes.cc'],
            #'twriter_test ' : ['trigger_test.cc', 'trigger_classes.cc'],
            }
            
for progname,srcs in programs.items():
    prog = menv.Program(progname,srcs+[lib])
    menv.Alias(progname,prog)

