import os
Import('env lib')

menv = env.Clone()
menv.Append(CPPPATH=['#'],LIBS=['sndfile','boost_date_time',
	 			'boost_program_options'])

programs = {'mixer' : ['mixer.cc'],
            'delay' : ['delay.cc'],
            'writer' : ['writer.cc'],
            'offline_mixer' : ['offline_mixer.cc'],
            }

out = []
            
for progname,srcs in programs.items():
    prog = menv.Program(progname,srcs+[lib])
    menv.Alias(progname,prog)
    out.append(prog)

Return('out')

